Repository we-meetting/weMeet-frontend, pull requests merged in 2023-12, with the labels that each got.

#2 feat: add text common component
  index.html
  src/assets/logo.svg
  src/components/common/Text/index.tsx
  src/components/common/Text/styled.ts
  src/components/common/index.ts
  src/components/index.ts
  src/pages/main/index.tsx
  src/pages/main/styled.ts
Labels: ✨ 기능

#8 bug: text component font bug
  index.html
  package.json
  pnpm-lock.yaml
  src/components/common/Text/index.tsx
  src/components/common/Text/styled.ts
  src/pages/main/index.tsx
  src/styles/global.ts
Labels: ✨ 기능, 🐛 버그

#10 feat: navbar creation
  src/assets/index.ts
  src/components/common/Navbar/index.tsx
  src/components/common/Navbar/styled.ts
  src/components/common/index.ts
  src/constants/index.ts
  src/constants/navbarContents.ts
  src/pages/main/index.tsx
  src/styles/styled.d.ts
  src/styles/theme.ts
Labels: ✨ 기능, 🎨 디자인
