Repository we-meetting/weMeet-frontend, pull requests merged in 2024-01, with the labels that each got.

#19 feat: add recommand page
  index.html
  src/Router.tsx
  src/assets/allSearchIcon.svg
  src/assets/enjoySearchIcon.svg
  src/assets/index.ts
  src/assets/restaurantSearchIcon.svg
  src/assets/searchIcon.svg
  src/components/common/Navbar/index.tsx
  src/components/common/Navbar/styled.ts
  src/components/common/PlaceCard/index.tsx
  src/components/common/PlaceCard/styled.ts
  src/components/common/Text/index.tsx
  src/components/common/Text/styled.ts
  src/components/index.ts
  src/components/layouts/Container/index.tsx
  src/components/layouts/DefaultLayout/index.tsx
  src/components/layouts/DefaultLayout/styled.ts
  src/components/layouts/index.ts
  src/components/main/searchSection/index.tsx
  src/components/main/searchSection/styled.ts
  src/components/recommend/RecommendForm/index.tsx
  src/components/recommend/RecommendForm/styled.ts
  src/components/recommend/index.ts
  src/constants/index.ts
  src/constants/navbarContents.ts
  src/constants/recommendContents.ts
  src/constants/searchbarContents.ts
  src/constants/searchbarContents.tsx
  src/hooks/index.ts
  src/hooks/useFadeInScroll.tsx
  src/hooks/useGetWindowSize.ts
  src/pages/index.ts
  src/pages/main/styled.ts
  src/pages/recommend/index.tsx
  src/pages/recommend/styled.ts
  src/providers/modal/index.tsx
  src/styles/global.ts
  src/styles/styled.d.ts
  src/styles/themes/light.ts
Labels: ♻️ 리팩토링, ✨ 기능, 🎨 디자인, 🐛 버그

#21 feat: add map page
  .gitignore
  package.json
  pnpm-lock.yaml
  src/Router.tsx
  src/assets/index.ts
  src/assets/marker.svg
  src/components/common/Navbar/index.tsx
  src/components/common/Navbar/styled.ts
  src/components/main/searchSection/index.tsx
  src/components/main/searchSection/styled.ts
  src/constants/navbarContents.ts
  src/pages/index.ts
  src/pages/map/index.tsx
  src/pages/map/styled.ts
  src/stores/index.ts
  src/stores/mapKeyword.ts
  src/stores/search.ts
  src/vite-env.d.ts
  tsconfig.json
Labels: ✨ 기능, 🎨 디자인

#23 feat(page): add plan page
  .env.sample
  .eslintrc
  .gitignore
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/api/api.ts
  src/api/index.ts
  src/api/recommend.ts
  src/api/search.ts
  src/assets/index.ts
  src/components/common/Input/index.tsx
  src/components/common/Input/styled.ts
  src/components/common/Marker/index.tsx
  src/components/common/Marker/styled.ts
  src/components/common/Navbar/index.tsx
  src/components/common/Spinner/index.tsx
  src/components/common/Spinner/styled.ts
  src/components/common/Text/index.tsx
  src/components/common/index.ts
  src/components/main/searchSection/index.tsx
  src/components/recommend/RecommendForm/index.tsx
  src/components/recommend/RecommendForm/styled.ts
  src/constants/recommendContents.ts
  src/hooks/index.ts
  src/hooks/queries/index.ts
  src/hooks/queries/useRecommendMutation.ts
  src/hooks/queries/useSearchQuery.ts
  src/hooks/useDebounce/index.tsx
  src/hooks/useFadeInScroll/index.tsx
  src/hooks/useGetWindowSize/index.ts
  src/pages/map/index.tsx
  src/pages/recommend/index.tsx
  src/pages/recommend/styled.ts
  src/stores/index.ts
  src/stores/makerInfo.ts
  src/stores/mapKeyword.ts
  src/stores/search.ts
  src/styles/global.ts
  src/styles/styled.d.ts
  src/styles/themes/light.ts
  src/styles/toastify.ts
  src/vite-env.d.ts
Labels: ♻️ 리팩토링, ✨ 기능, 🎨 디자인

#25 feat: backend search connection
  src/components/common/Navbar/index.tsx
  src/components/common/Navbar/styled.ts
  src/components/common/PlaceCard/index.tsx
  src/components/common/PlaceCard/styled.ts
  src/components/main/searchSection/index.tsx
  src/components/main/searchSection/styled.ts
  src/constants/navbarContents.ts
  src/pages/map/index.tsx
  src/stores/index.ts
  src/stores/map.ts
  src/stores/mapKeyword.ts
  src/stores/search.ts
  src/styles/toastify.ts
Labels: ✨ 기능, 🎨 디자인

#27 feat: add workflows
  .github/workflows/build.yml
  .github/workflows/release.yml
  package.json
  pnpm-lock.yaml
  src/components/common/Marker/index.tsx
  src/components/common/Marker/styled.ts
  src/pages/map/index.tsx
Labels: 🚀 CI/CD

#28 Feature/15 add login modal and register modal
  pnpm-lock.yaml
  src/api/api.ts
  src/api/auth.ts
  src/api/useAuth.ts
  src/components/common/AuthForm/index.tsx
  src/components/common/AuthForm/styled.ts
  src/components/common/Navbar/index.tsx
  src/components/common/index.ts
  src/components/common/modals/DefaultModal/index.tsx
  src/components/common/modals/DefaultModal/styled.ts
  src/components/common/modals/LoginModal/index.tsx
  src/components/common/modals/RegisterModal/index.tsx
  src/components/common/modals/SearchModal/index.tsx
  src/components/common/modals/SearchModal/styled.ts
  src/components/main/searchSection/styled.ts
  src/main.tsx
  src/styles/styled.d.ts
  src/styles/themes/light.ts
  tsconfig.json
Labels: ✨ 기능, 🎨 디자인

#31 bug: style bug
  pnpm-lock.yaml
  src/api/useAuth.ts
  src/components/common/Navbar/index.tsx
  src/components/common/PlaceCard/styled.ts
  src/components/common/modals/LoginModal/index.tsx
  src/components/common/modals/RegisterModal/index.tsx
  src/components/common/modals/SearchModal/index.tsx
  src/components/common/modals/SearchModal/styled.ts
  src/components/main/searchSection/index.tsx
  src/components/main/searchSection/styled.ts
  src/hooks/queries/useRecommendMutation.ts
  src/pages/recommend/index.tsx
  src/stores/index.ts
  src/stores/recommend.ts
Labels: ✨ 기능, 🎨 디자인, 🐛 버그
